spring:
  application:
    name: yupao-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://user.kallinchen.cn:3306/yupao?useSSL=false&allowPublicKeyRetrieval=true'
    username: root
    password: Cyx990924+-408
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: user.kallinchen.cn
    database: 1
    password: 19990924
server:
  address: 0.0.0.0
  port: 8088
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
